//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emarketing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEmarketingEntities : DbContext
    {
        public dbEmarketingEntities()
            : base("name=dbEmarketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_admin> tb_admin { get; set; }
        public DbSet<tb_category> tb_category { get; set; }
        public DbSet<tb_product> tb_product { get; set; }
        public DbSet<tb_user> tb_user { get; set; }
    }
}
