//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emarketing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_category
    {
        public tb_category()
        {
            this.tb_product = new HashSet<tb_product>();
        }
    
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string cat_image { get; set; }
        public Nullable<int> cat_fk_ad { get; set; }
        public Nullable<int> cat_status { get; set; }
    
        public virtual tb_admin tb_admin { get; set; }
        public virtual ICollection<tb_product> tb_product { get; set; }
    }
}
